### ISSUE TITLE
couldn't be installed on OS X 10.9 Mavericks

### ISSUE THREAD

**Issue by copuzzle** [abaelhe/amysql#1]
python setup.py install

**Comment by awnion** [comment]
Compilation error:

```
./amysql.c:1657:6: error: non-void function 'Con_PacketRecv' should return a value [-Wreturn-type]
                                        return;
```

PS Is this project alive or not?

**Comment by abaelhe** [comment]
adjust compiler arguments and have a try.
MAY compatible with OSX at next version .

**Comment by abaelhe** [comment]
adjust compiler arguments and have a try.
MAY compatible with OSX at next version .
